all: mandelbrot_sequential.o mandelbrot_mpi.o mandelbrot_mpiOpenmp.o

mandelbrot_sequential.o: mandelbrot_sequential.c
	mpicc mandelbrot_sequential.c -o mandelbrot_sequential.o

mandelbrot_mpi.o: mandelbrot_mpi.c
	mpicc mandelbrot_mpi.c -o mandelbrot_mpi.o

mandelbrot_mpiOpenmp.o: mandelbrot_mpiOpenmp.c
	mpicc -fopenmp mandelbrot_mpiOpenmp.c -o mandelbrot_mpiOpenmp.o

clean:
	rm -rf *.o